server:
  port: 20000
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000
    fetch-registry: false
    register-with-eureka: true
